platform :ios, '7.0'
pod 'Canvas'
pod 'TPKeyboardAvoiding'
pod 'SOCKit', '~> 1.1'
pod 'AFNetworking'
pod 'SDWebImage', '~> 3.5'
pod 'NSDate+TimeAgo', '~> 1.0.2'
pod 'ACSimpleKeychain'
pod 'TTTAttributedLabel'
pod 'ReactiveCocoa'
pod 'Mantle'
